---
- name: Create app directory
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: "0755"
    owner: mukesh
    group: mukesh

- name: Create .env file
  template:
    src: "templates/code.env.j2"
    dest: "{{ app_dir }}/.env"
    force: true
    owner: mukesh
    group: mukesh
    mode: "0644"
