---
dependencies: []

galaxy_info:
  role_name: nginx
  author: adex
  description: Nginx installation module
  license: "license (BSD, MIT)"
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
