---
nginx_root_group: root
nginx_user: nginx
nginx_conf_file_path: /etc/nginx/nginx.conf
nginx_conf_path: /etc/nginx/conf.d
nginx_pidfile: /var/run/nginx.pid
nginx_vhost_path: /etc/nginx/conf.d
nginx_default_vhost_path: /etc/nginx/conf.d/default.conf
nginx_mime_file_path: /etc/nginx/mime.types
nginx_file_mode: "0644"
nginx_directory_mode: "0755"
nginx_remove_default_vhost: true
nginx_amazon2_repo_enabled: true
nginx_redhat_repo_enabled: false
