---
- name: Create app directory
  file:
    path: /home/mukesh/app
    state: directory
    mode: '0755'
    owner: mukesh
    group: mukesh

- name: Install PostgreSQL and related packages
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: latest
    update_cache: true

- name: Install python packages
  pip:
    name: psycopg2-binary

- name: Create PostgreSQL user for the application
  become: true
  become_user: postgres
  postgresql_user:
    name: novelty
    password: novelty123

- name: Create database for the application
  become: true
  become_user: postgres
  postgresql_db:
    name: novelty

- name: Ensure the new user has access to the database
  become: true
  become_user: postgres
  postgresql_privs:
    db: novelty
    role: novelty
    objs: ALL_IN_SCHEMA
    privs: ALL
  notify: Restart psql
