---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Check if gather_facts is enabled
  ansible.builtin.fail:
    msg: "Fact gathering is disabled. This roles requires gather_facts to be enabled. Please enable fact gathering using 'gather_facts: true' in your playbook."
  when: ansible_facts == {}

- name: Install nginx for windows
  ansible.builtin.include_tasks: Windows.yml
  when: ansible_os_family == "Windows"

- name: Nginx for Linux
  ansible.builtin.include_tasks: linux.yml
  when: ansible_system == "Linux"

- ansible.builtin.import_tasks: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ nginx_root_group }}"
    mode: "0644"
  notify:
    - Reload nginx

- name: Ensure nginx service is running as configured.
  service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
