---
- hosts: node
  become: true
  become_user: mukesh
  become_method: sudo
  gather_facts: true
  roles:
    - nginx
    - psql
  vars:
    ansible_shell_executable: /bin/bash
    ansible_user: mukesh