#checkov:skip=CKV_GHA_3: "Suspicious use of curl with secrets"
#checkov:skip=CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
name: ROLLBACK DEPLOYMENT
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write

env:
  dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
  dockerUsername: mukesh1111

jobs:
  rollback:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.dockerUsername }}
          password: ${{ env.dockerHubToken }}

      - name: Get previous image tag
        id: prev-tag
        run: |
          # Fetch all tags and sort them to get the previous tag
          TAGS=$(curl -s https://registry.hub.docker.com/v1/repositories/${{ env.dockerUsername }}/novelty/tags | jq -r '.[].name' | sort -V)
          PREV_TAG=$(echo "$TAGS" | grep -B1 "${{ github.sha }}" | head -n 1)
          echo "Previous tag: $PREV_TAG"
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV

      - name: Pull previous Docker image
        run: docker pull ${{ env.dockerUsername }}/novelty:${{ env.PREV_TAG }}

      - name: Tag previous Docker image as latest
        run: |
          docker tag ${{ env.dockerUsername }}/novelty:${{ env.PREV_TAG }} ${{ env.dockerUsername }}/novelty:latest
          docker push ${{ env.dockerUsername }}/novelty:latest
