#checkov:skip=CKV_GHA_3: "Suspicious use of curl with secrets"
#checkov:skip=CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
name: ROLLBACK DEPLOYMENT
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write

env:
  dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
  dockerUsername: mukesh1111
  prevImage: faa44680605849bd7c23c1bd6cee123c156ee0b8

jobs:
  rollback:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.dockerUsername }}
          password: ${{ env.dockerHubToken }}

      - name: Pull previous Docker image
        run: docker pull ${{ env.dockerUsername }}/novelty:${{ env.prevImage }}

      - name: Tag previous Docker image as latest
        run: |
          docker tag ${{ env.dockerUsername }}/novelty:${{ env.PREV_TAG }} ${{ env.dockerUsername }}/novelty:latest
          docker push ${{ env.dockerUsername }}/novelty:latest
