#checkov:skip=CKV_GHA_3: "Suspicious use of curl with secrets"
#checkov:skip=CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
name: ROLLBACK DEPLOYMENT
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write

env:
  userName: mukesh
  serverIp: ${{ secrets.SERVER_IP }}
  sshKey: ${{ secrets.NOVELTY}}
  dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
  dockerUsername: mukesh1111
  prevImage: faa44680605849bd7c23c1bd6cee123c156ee0b8
  newImage: 6d5e746e05bb9914198b239b33a58ff929759406

jobs:
  rollback:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.dockerUsername }}
          password: ${{ env.dockerHubToken }}

      - name: Set up SSH key
        run: |
          echo "${{ env.sshKey }}" >> novelty.pem
          sudo chmod 400 novelty.pem

      - name: Pull previous Docker image
        run: docker pull ${{ env.dockerUsername }}/novelty:${{ env.prevImage }}

      - name: Tag previous Docker image as latest
        run: |
          docker tag ${{ env.dockerUsername }}/novelty:${{ env.prevImage }} ${{ env.dockerUsername }}/novelty:${{ env.newImage }}
          docker push ${{ env.dockerUsername }}/novelty:${{ env.newImage }}

      - name: executing remote ssh commands using password
        run: |
          sleep 20
          ssh -i novelty.pem ${{env.userName}}@${{ env.serverIp }} 'bash -s ${{ env.newImage }}' < deploy.sh
