---
name: NODE DEPLOYMENT
run-name: "[${{ github.event_name }} - ${{ github.ref_name }}]"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

env:
  userName: mukesh
  workDir: /home/mukesh/app
  serverIp: ${{ secrets.SERVER_IP }}
  nodeversion: 20
  githubToken: ${{ secrets.TOKEN_GITHUB }}
  password: ${{ secrets.PASSWORD }}
  sshKey: ${{ secrets.NOVELTY}}
  branchName: main
  dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
  dockerUsername: mukesh1111
  appName: node-app

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v6
        env:
          DEFAULT_BRANCH: ${{ env.branchName }}
          FILTER_REGEX_INCLUDE: "^src/.*"
          GITHUB_TOKEN: ${{ env.githubToken }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false

  build:
    name: Deployment of nocode backend
    runs-on: ubuntu-22.04
    needs: lint

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install sshpass
        run: |
          sudo apt update
          sudo apt install sshpass -y
          sudo apt install ansible -y
          ansible --version

      - name: Set up SSH key
        run: |
          echo "${{ env.sshKey }}" >> novelty.pem
          sudo chmod 400 novelty.pem

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/configure.yml -i ansible/inventory.txt --extra-vars 'ansible_sudo_pass=${{env.password}}' --private-key novelty.pem
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.dockerUsername }}
          password: ${{ env.dockerHubToken }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.dockerUsername }}/${{ env.appName }}:${{ github.sha }}

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --include="deploy.sh" --include="docker-compose.yml"
          path: ./
          remote_path: ${{ env.workDir }}
          remote_host: ${{ env.serverIp }}
          remote_port: 22
          remote_user: ${{ env.userName }}
          remote_key: ${{ env.sshKey}}
